.travis.yml
This will build Meyda against node 6 in Travis. Context: Node 6 was released earlier this evening CEST. Fingers crossed.
=> Adds Node 6 as a CI target

Gulpfile.js, src/featureExtractors.js, src/index.js, webpack.config.js
Allows web dist to be built as UMD (CommonJS, AMD and as global variable), which has greater compatibility over the current `window.Meyda` only solution.
This also allows for meyda's web build to use tree shaking, removing redundant imports and reducing filesize.
This does NOT introduce breaking changes
Completes #203
=> Build web dist as UMD

package.json, webpack.config.js
The serve command assumed python was installed on the user's machine.
Webpack offer a dev server which can serve files and rebuild using webpack at the same time, suggest we use that instead, this required an update to webpack 2.
No breaking changes.
=> gh-pages use webpack-dev-server (update to webpack 2)

docs/guides/offline-cli.md
The correct npm command is `npm install`
=> fix typo in offline-cli guide

.eslintrc.json
Minor fix due to deprecation of .eslintrc files without extension: https://eslint.org/docs/user-guide/configuring#configuration-file-formats
=> Added extension (.json) to .eslintrc

src/extractors/zcr.js
ZCR was in some cases missing one zero crossing per buffer by overrunning the buffer on the final iteration. This commit removes the buffer overrun case.
=> Fix bug in ZCR

package-lock.json, package.json
Fixes cosMap declaration error in the dct module when in strict mode.
We fixed this on dct's side but never updated Meyda with the new package 🤷‍♂
=> chore(dct): bumps dct version from 0.0.3 to 0.1.0

src/main.js, src/meyda-wa.js
As stated on the tin: allowing users to set the number of MFCCs the analyzer returns.
Prior to this change, it would default to 13. However, this limitation is not ideal, as many applications require a different amount of coefficients.
To return N coefficients, we need at least N mel bands (although usually we want to have more bands, as we discard the higher ones - perhaps a TODO for later).
With this change I'm also making sure users don't need to set `melBands` if they specify a number of coefficients which is higher than the default number of mel bands (`26`).
Run `npm test`: `97 passing (140ms)`
Run `npm build` and use the code just built in a dummy project:
```
const analyzer = Meyda.createMeydaAnalyzer({
audioContext: audioCtx,
source: audioSrc,
bufferSize: 512,
// I can now …
```
=> Allow setting number of mfcc coefficients in Analyzer constructor

.travis.yml, package-lock.json, package.json
I contributed to a repository using semantic-release recently and it was really easy to get the change merged and deployed. I think we should consider using it.
The general idea is that commit messages are formatted in a specific way such that it's clear exactly what kind of change this makes to the repo (major, minor, patch, chore, etc). Then in CI, the script will check what kind of release should be made, and generate a changelog, a git tag, and push to the registry. No need to manually do releases anymore! It's easy to make well-formatted commit messages using the commitizen library, which will prompt you with various questions to form the message.
Let me know what you think.
=> Add semantic release

.npmrc, .travis.yml, package-lock.json, package.json
This'll make releasing Meyda much easier. If we stick to a format for our commit messages, Travis can automatically deploy new versions of Meyda without waiting for us to think about things. Thinking about releases too much has reduced our velocity significantly - I think there's a lot to be said for unsentimental release, and I'll let [someone else say it](https://blog.logrocket.com/unsentimental-versioning/).
=> Add commitlint

.dependabot/config.yml
As of now, dependabot config is stored in the dependabot service. This PR puts the config with the code, and configures dependabot to use commit messages the way we want.
=> Explicitly configure dependabot

bin/cli.js
Added a new CLI option and configured the properties to set the value for `numberOfMFCCCoefficients` as supplied to the CLI or fall back to the default value of `13`.
Closes #546.
=> Add CLI option to configure numberOfMFCCCoefficients

package-lock.json, package.json, webpack.config.js
webpack 5 removed a terser option called sourceMap, source maps are now generated based on the value
we set for 'devtool'
in addition, webpack 5 bundles `terser-webpack-plugin`, so we no longer need a separate dependency declaration on it.
=> build(webpack): minor correction to terser config

docs/guides/offline-node.md
I wrote a post about loading audio from disk in node. We've had requests for this kind of doc
before, so I think we should link out to it from the node guide.
fix #271
=> docs(node guide): link to audio loading post

src/extractors/mfcc.js
Because we did a prettier update, prettier made some changes. They're in the first commit - the actual change is in the second commit.
We had two imports:
```
import freqToMel from '../utilities';
import melToFreq from '../utilities';
```
Because this isn't a destructure import, the meaning here is that we're importing the default export from utilities twice with two different names. I assume the intended behaviour would be accomplished with the following:
```
import { freqToMel, melToFreq } from '../utilities';
```
However, we're actually not using the imports, so rather than fixing the line, I removed both lines.
=> chore(mfcc-extractor): run prettier so that next commit is clear

__tests__/index.js, src/index.js
The prettier rewrite in #823 decided to export an es6 module rather than our default. I didn't
expect prettier to change behaviour, and I didn't catch it. This means that meyda@5.1.4 and
meyda@5.1.5 are bad, and will need to be deprecated. This commit introduces a test that will catch
this issue in the future.
=> fix(package exports): revert prettier rewrite

docs/getting-started.md
We have typescript type definitions, but we haven't told anyone. Lets start telling them.
fix #833
=> docs(getting-started): instruct users how to install typescript defintions

docs/audio-features.md
Loudness has been incorrectly documented as having a range of 0-1 per band and 24 in total. In fact,
loudness is not normalised. I replaced the range section with a description of how to approach
consuming the loudness data in different use cases.
fix #288
=> docs(loudness): document loudness range

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/merge-build.yml, .travis.yml, package.json
fix #840
This PR will contain all the commits for the migration from Travis.
TODO:
* We don't actually have Prettier in Meyda.
=> Switch from Travis CI to GitHub Actions

.travis.yml
RIP, you've served us well for over 2.5k builds and nearly 6 years.
=> ci(travis): remove travis.yml

bin/cli.js, bin/wav-loader.js
The CLI always assumed that the sample rate of the wav file thats getting read is 44100hz. This small improvement reads the sample rate from the wav file and sets it
=> Recognize sample rate of wav file

bin/cli.js
There was an issue with the wav file being processed wrongly. It first processed the new chunk before it concated it to the previous buffer. If there is still something in the buffer, it will get processed after the the chunk, therefore changing the order of the data. It should be processed in the order it got in. Not sure if my explanation is clear, please let me know if its confusing and I'll try to improve it
=> Fix issue with cli wrongly processing wav

src/utilities.js
A constant exists in the formula for converting between hz and the mel scale, which Meyda has had
set to 1125. The mel-scale is not standardised, but it seems that the most popular formula comes
from "Speech communication: human and machine" by Douglas O'Shaughnessy. That formula has the
constant as 1127. The issue mentioned below was opened, and suggests that we converge on
O'Shaughnessy's constant. This commit implements that change.
BREAKING CHANGE: A change in how Meyda performs frequency to mel scale conversion will result in
different mel-values between this and previous versions of Meyda.
fix #458
=> fix(mfcc): adjust mfcc constant

.github/dependabot.yml
I just triggered a release of meyda because dependabot updated a non-dev dependency of the docs package. That isn't ideal. From now on, all updates of all deps in docs will be tagged with "docs"
=> chore(semantic-release): disable for docs

package.json, tsconfig.json
src used to be in esmodules and was exposed, but now that we're in typescript, we have to build them.
fixes: #1052
=> fix(modules): expose esmodule

__tests__/extractors/positiveFlux.ts, __tests__/extractors/spectralFlux.ts, docs/audio-features.md, src/extractors/positiveFlux.ts, src/extractors/spectralFlux.ts, src/featureExtractors.ts, src/main.ts
Spectral flux has an implementation error - it was referring to a null object. I fixed that, but then realized that spectral flux is doing the euclidean distance between two _signals_, not two spectra, which seems to be incorrect from my reading. We'll need to review and fix this. I think because it's changing what the original behavior was if we were to switch to spectra, this should be considered a breaking change.
fix #236
=> Spectral Flux is weird and needs a little bit of love probably

__tests__/extractors/spectralCrest.ts, docs/audio-features.md, src/extractors/spectralCrest.ts, src/featureExtractors.ts, src/main.ts
This adds a new extractor for computing the [crest](https://www.mathworks.com/help/audio/ug/spectral-descriptors.html#SpectralDescriptorsExample-7) of the amplitude spectrum. In theory, the descriptor will indicate if there is a peaky bin compared to the overall spectral curve.
Tests pass, and using the provided valid ampSpectrum frame I derived the value that should be returned by first checking in Max with [FrameLib](https://github.com/AlexHarker/FrameLib) as well as in Python.
In terms of style I opted for something quite terse and leveraged `.forEach()`. I hope this is okay.
=> feat: spectral crest extractor
