bin/cli.js
bin/wav-loader.js
src/utilities.js

This should theoretically be able to read wav files at the right bit-depth. Average features look implausible.
I don't think it quite works because on the same file encoded at 16, 24, and 32 bits have different numbers of frames :frowning: Needs more work.

adds support for n-bit wav files

---

bower.json

Update author email address

---

bower.json
package.json
readme.md

Updates readme and version on `bower.json` and `package.json`

Pre release

---

test.html

Tried to comment where appropriate :) 
Think there may be more that can be done performance wise. Would be a cool project to get involved with!

Attempted perfomance boost

---

src/utilities.js

Windowing functions weren't being applied!

---

index.html

Adds a select all button to the github pages branch.
@nevosegal

Can I have this please?

---

src/extractors/spectralFlux.js

Our first feature extractor in MONTHS! :D

Adds spectral flux feature extractor

---

package.json

https://greenkeeper.io/
Fixes #177

chore(package): update codeclimate-test-reporter to version 0.4.1

---

Gulpfile.js
package.json
src/main.js
webpack.config.js

Update to use jsfft from npm and switch build process to webpack 2

---

main.js
src/main.js

Changed the frequency axis to work on a logarithmic scale to better display the lower part of the spectrum. Also, removed some code that caused some errors and seemed unnecessary. If you think we should keep it let me know.

log frequency axis + remove redundant code

---

index.html
src/main.js
styles.css

Adds a legend to show what the arrows represent in the demo.
Moves styles out to a stylesheet.
Rewrites resize code for succinctness.

gh-pages add showcase legend, rewrite resize code

---

.travis.yml
CONTRIBUTING.md
package.json
readme.md

Prepares to move to a [github.com/meyda](https://github.com/meyda)

Migrate to meyda/meyda

---

package.json
src/main.js

This branch removes the external fft library we've been using and instead uses our very own fft library - [fftjs](https://github.com/nevosegal/fftjs) :1st_place_medal:

Adds fftjs and remove jsfft-for-meyda

---

.travis.yml

Sorry, I didn't see the comment in #215 til now!

Turn off CodeClimate

---

bin/cli.js
src/main.js
src/meyda-wa.js
src/utilities.js
test/featureExtractors.js
test/utilities.js

Fixes #214 
CLI example:
```
> meyda ../audio/simple_piano.wav spectralCentroid --bs=4096          
=========
Meyda CLI
=========
Buffer size: 4096
Hop size: 4096
Windowing function: hanning
Will extract:
spectralCentroid 
Starting extraction...
|----------------------|
Extraction finished.
21 frames analysed.
*********spectralCentroid*********
212.29480283473072
226.14276195697147
243.5170886257632
239.29269272739805
202.82786881033803
230.65842128691256
206.99184988680878
232.1087538032745
209.12762019268362
196.79483907418867
215.40387698415668
189.71890913379028
196.88050371829087
180.90973828656496
177.69390401561895
200.69076300528846
183.54836467326388
159.66518364328704
154.62522510265816
177.14018241411935
165.11374531554597
Average spectralCentroid: 200.05462359484068
> meyda …
```

Add hopSize option to browser and CLI audio analyzers

---

index.html
src/main.js
styles.css

Add chroma demo

---

src/extractors/mfcc.js
src/main.js
test/extractors/mfcc.js

@nevosegal and I paired on enabling the user to set the number of mfccs.
Fixes #224 
Also does a nice lil refactor in main.

User can set number of MFCCs

---

docs/guides/online-web-audio.md

I wrote this tutorial on how to use Meyda in Web Audio. It's based on [this glitch project][glitch-project], which plays audio in a HTML audio element and pipes it through Meyda, which displays the `rms` in a HTML range element. Most straightforward round-trip through Meyda I could think of, not involving explaining any of the more complex audio features, or any particularly weird signal processing stuff, but if you can think of a simpler one, please suggest it.
I'd really appreciate if you could run through the tutorial and check that it makes sense and hasn't made any assumptions about the knowledge the user has.
If you could test the tutorial with your browser/os combination, that'd be sweet too.
[glitch-project]: https://glitch.com/edit/#!/meyda-tutorial

Add tutorial on using meyda in web audio

---

docs/getting-started.md
docs/guides/offline-cli.md

Adds a tutorial for how to use Meyda's CLI

Add offline cli tutorial

---

readme.md

We removed codeclimate some time ago as it was breaking the build, lets remove the badges for it too.

Remove badges for CodeClimate

---

docs/guides/offline-node.md

Updated .get to .extract, for the guide on using in nodeJS.

updated .get to .extract in nodejs guide

---

package-lock.json
package.json

That forced us to update Browserify to from `14.1.0` to `16.2.3`.

fix vulnerabilities npm was complaining about

---

docs/index.md
readme.md

I think it would be good to direct people to our slack channel so they can talk about Meyda. What do you all think?

Add a link to our Slack channel

---

docs/README.md
docs/_includes/showcase.html
docs/assets/main.css
docs/assets/main.js
docs/package-lock.json
docs/src/main.js

Display MFCC in Docs Visualizer

---

src/main.js
src/meyda-wa.js

Allow setting number of mfcc coefficients in Analyzer constructor

---

src/main.js
src/meyda-wa.js

I merged this to v5 without first checking that it was squashed

 Allow setting number of mfcc coefficients in Analyzer constructor

---

src/main.js

I added some detail on windowing which was merged in #316, but I didn't actually commit the source. Here's that.

(docs): Add the source esdoc for generated reference

---

package-lock.json
package.json

The idea here is that we always know whether a commit has an impact on the version (i.e. is a
breaking change, adds a feature, etc) so that we can automatically release a new version.

chore: add commitlint

---

docs/getting-started.md

docs(getting-started): add installation instructions

---

src/windowing.js

fix(blackman windowing): allow odd-length windows

---

src/index.js

docs(web bundling): clarify the purpose of indexjs as web entrypoint

---

.github/workflows/commitlint.yml

ci(commitlint): add github action to lint commits and provide better feedback

---

package-lock.json
package.json

We don't use webpack anymore, we don't need those deps

chore(webpack): remove webpack deps

---

bin/cli.js
bin/wav-loader.js

Thanks @Pita - these went into one branch so that only one release is triggered. This PR should publish the next version of Meyda with your fixes. Thanks again for contributing!!

CLI fixes from @Pita

---

docs/audio-features.md

docs(rms): correct range information

---

docs/major-changes-policy.md

major changes policy

---

README.md
docs/index.md
docs/showcase.md

docs(showcase): add showcase signup link

---

.husky/commit-msg
package.json

husky wasn't working since we didn't update our config to be comatible with v6+

chore(husky): use husky properly

---

docs/src/audio.ts
package-lock.json
package.json

Doing this manually since it introduces a new rule that we failed on one line and had to ignore.

bump @typescript-eslint/eslint-plugin

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/merge-build.yml
docs/package.json
package-lock.json
package.json
rollup.config.mjs

fix(web bundle): use node resolve so fftjs is found
